apiVersion: v1
kind: Secret
metadata:
  name: wejay-secrets
  namespace: wejay
type: Opaque
stringData:
  spotify-client-id: "e19d321094614f8f97a63eb0d639dba4"
  spotify-client-secret: "0fa3897f9e9f4ad689b9f68fb277a44f"
  berget-api-key: "sk_ber_u8o9YMCI94Y9PlwZYAtevs1EgOCxljokjMR_ec851ecec626f897"